
services:
  # The main FastAPI web server
  mcp_server:
    build: .
    container_name: mcp_server_api
    ports:
      - "1314:8002"
    env_file: .env
    volumes:
      - ./app:/code/app
    networks: 
      - mcp_network
    depends_on:
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # The Redis database
  redis:
    image: redis:7.2-alpine
    container_name: mcp_redis
    ports:
      - "1315:6379"
    volumes:
      - redis_data:/data
    networks: 
      - mcp_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50

  # The Celery worker service
  celery_worker:
    build: .
    container_name: mcp_celery_worker
    command: celery -A app.worker worker --loglevel=info -P solo
    env_file: .env
    volumes:
      - ./app:/code/app
    networks: 
      - mcp_network
    depends_on:
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  mcp_network:
    driver: bridge

volumes:
  redis_data: